apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-blue
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-demo
      version: blue
  template:
    metadata:
      labels:
        app: cicd-demo
        version: blue
    spec:
      containers:
        - name: cicd-demo
          image: mydockerkdb/cicd-demo:latest
          ports:
            - containerPort: 5000
