apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: cicd-demo
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010
